[tools]
python = "latest"
node = "lts"
terraform = "latest"
uv = "latest"
bun = "latest"
ripgrep = "latest"
tmux = "latest"
go = "latest"
rust = "latest"
psqldef = "latest"

[settings]
experimental = true
python.uv_venv_auto = true
